import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  lang: 'zh-CN',
  title: "BinWind",
  description: "一条路的终点，是另一条路的起点",
  appearance: true,
  lastUpdated: false,
  head:[
    ['link',{rel:'icon',href:'/images/logo.png'}], 
  ],
  themeConfig: {
    outline: 'deep',
    outlineTitle: '目录',
    docFooter: {       
      prev: false,
      next: false
    },

    // https://vitepress.dev/reference/default-theme-config
    nav: [
      { text: '首页', link: '/index' },
      { text: 'AI', link: '/AI/index' },
      { text: '编程', link: '/Code/index' },
      { text: '服务器', link: '/Server/index' },
      { text: '设计', link: '/Design/index' },
      { text: '应用', link: '/APP/index' },
      { text: '书籍', link: '/Book/index' },
      { text: '视频', link: '/Video/index' },
      { text: '其他', link: '/Other/index' },
    ],
    sidebar: {
      '/AI/': [
        {
          text: '前言',
          link: '/AI/index',
          collapsed: false,
        },
        {
          text: 'AI 全流程讲解',
          collapsed: false,
          items: [
            { text: '前言', link: '/AI/full-process' },
            { text: 'AI 开发环境搭建：GPU 选型与云平台对比', link: '/AI/1' },
            { text: '数据采集与清洗实战', link: '/AI/2' },
            { text: '数据标注全流程指南', link: '/AI/3' },
            { text: '大模型选型方法论', link: '/AI/4' },
            { text: '模型训练关键超参数详解', link: '/AI/5' },
            { text: '模型评估指标与基准测试', link: '/AI/6' },
            { text: 'AI 模型量化技术：GGUF / AWQ / GPTQ', link: '/AI/7' },
            { text: 'vLLM 高性能推理部署', link: '/AI/8' },
            { text: '模型监控与持续迭代方案', link: '/AI/9' },
          ]
        },
        {
          text: '大模型微调',
          collapsed: false,
          items: [
            { text: '前言', link: '/AI/model-finetuning' },
            { text: 'LoRA 微调原理与调参实战', link: '/AI/10' },
            { text: 'QLoRA：消费级显卡微调大模型', link: '/AI/11' },
            { text: '指令微调（Instruction Tuning）数据构造指南', link: '/AI/12' },
            { text: 'DPO 偏好对齐：从原理到实战', link: '/AI/13' },
            { text: 'LLaMA-Factory 一站式微调上手', link: '/AI/14' },
          ]
        },
        {
          text: 'Prompt 与 RAG',
          collapsed: false,
          items: [
            { text: 'Prompt Engineering 提示词工程精要', link: '/AI/15' },
            { text: 'RAG 检索增强生成：从零搭建知识库问答', link: '/AI/16' },
            { text: 'Function Calling 与 Tool Use 开发指南', link: '/AI/17' },
          ]
        },
        {
          text: 'Agent 开发',
          collapsed: false,
          items: [
            { text: 'AI Agent 开发实战：从 ReAct 到 Multi-Agent', link: '/AI/18' },
          ]
        },
      ],
      '/Code/': [
        {
          text: '前言',
          link: '/Code/index',
          collapsed: false,
        },
        {
          text: 'Python',
          collapsed: false,
          items: [
            { text: '前言', link: '/Code/python/index' },
            { text: 'Python 环境安装与配置', link: '/Code/python/1' },
            { text: '变量、数据类型与运算符', link: '/Code/python/2' },
            { text: '条件判断与循环控制', link: '/Code/python/3' },
            { text: '函数定义与参数详解', link: '/Code/python/4' },
            { text: '面向对象编程基础', link: '/Code/python/5' },
            { text: '模块与包管理', link: '/Code/python/6' },
            { text: '文件读写与路径操作', link: '/Code/python/7' },
            { text: '异常处理与调试', link: '/Code/python/8' },
            { text: '装饰器（Decorator）完全指南', link: '/Code/python/9' },
            { text: '生成器与迭代器', link: '/Code/python/10' },
            { text: '列表 / 字典 / 集合推导式', link: '/Code/python/11' },
            { text: '常用内置函数与标准库', link: '/Code/python/12' },
            { text: '字符串处理与正则表达式', link: '/Code/python/13' },
            { text: '虚拟环境与依赖管理', link: '/Code/python/14' },
            { text: 'Python 并发编程入门', link: '/Code/python/15' },
            { text: '类型注解与静态检查', link: '/Code/python/16' },
            { text: '单元测试', link: '/Code/python/17' },
            { text: 'requests 库：HTTP 请求实战', link: '/Code/python/18' },
            { text: '网页爬虫入门', link: '/Code/python/19' },
            { text: 'Selenium 动态网页爬取', link: '/Code/python/20' },
            { text: 'Pandas 数据分析入门', link: '/Code/python/21' },
            { text: 'NumPy 数值计算基础', link: '/Code/python/22' },
            { text: 'Flask Web 框架入门', link: '/Code/python/23' },
            { text: 'FastAPI 搭建高性能 API', link: '/Code/python/24' },
            { text: 'Python 脚本自动化实战', link: '/Code/python/25' },
          ]
        },
        {
          text: 'Java',
          collapsed: false,
          items: [
            { text: '前言', link: '/Code/java/index' },
            { text: 'Java 开发环境搭建', link: '/Code/java/1' },
            { text: '数据类型与变量', link: '/Code/java/2' },
            { text: '运算符与表达式', link: '/Code/java/3' },
            { text: '控制流程', link: '/Code/java/4' },
            { text: '面向对象基础', link: '/Code/java/5' },
            { text: '继承与多态', link: '/Code/java/6' },
            { text: '数组与集合框架', link: '/Code/java/7' },
            { text: '异常处理机制', link: '/Code/java/8' },
            { text: '泛型（Generics）详解', link: '/Code/java/9' },
            { text: 'Lambda 表达式与 Stream API', link: '/Code/java/10' },
            { text: '文件 IO 操作', link: '/Code/java/11' },
            { text: '日期时间处理', link: '/Code/java/12' },
            { text: '注解与反射', link: '/Code/java/13' },
            { text: 'Maven 构建工具实战', link: '/Code/java/14' },
            { text: 'Gradle 构建工具入门', link: '/Code/java/15' },
            { text: 'JUnit 5 单元测试', link: '/Code/java/16' },
            { text: '多线程与并发基础', link: '/Code/java/17' },
            { text: 'JVM 内存模型与 GC 基础', link: '/Code/java/18' },
            { text: 'JDBC 数据库操作', link: '/Code/java/19' },
            { text: 'MyBatis 持久层框架', link: '/Code/java/20' },
            { text: 'Spring Boot 快速上手', link: '/Code/java/21' },
            { text: 'Spring Boot 数据访问层', link: '/Code/java/22' },
            { text: 'Spring Boot RESTful API 实战', link: '/Code/java/23' },
            { text: 'Spring Security 认证与授权', link: '/Code/java/24' },
            { text: 'Java 项目打包与部署', link: '/Code/java/25' },
          ]
        },
        {
          text: 'PHP',
          collapsed: false,
          items: [
            { text: '部署', link: '/Code/php/index' },
            { text: '判断图片是正方形还是长方形', link: '/Code/php/1' },
            { text: '精确查询', link: '/Code/php/2' },
            { text: '数组去重的几种方法', link: '/Code/php/3' },
            { text: '防止 SQL 注入的最佳实践', link: '/Code/php/4' },
            { text: '文件上传安全处理', link: '/Code/php/5' },
            { text: '日期时间处理技巧', link: '/Code/php/6' },
            { text: '错误处理与日志记录', link: '/Code/php/7' },
            { text: '缓存技术详解', link: '/Code/php/8' },
            { text: 'JSON 处理常见问题', link: '/Code/php/9' },
            { text: '性能优化技巧', link: '/Code/php/10' },
            { text: '正则表达式实用技巧', link: '/Code/php/11' },
            { text: 'Session 与会话管理', link: '/Code/php/12' },
            { text: '中的引用与深浅拷贝', link: '/Code/php/13' },
            { text: '生成器（Generator）使用详解', link: '/Code/php/14' },
            { text: '闭包（Closure）与匿名函数', link: '/Code/php/15' },
            { text: 'Trait 特性详解', link: '/Code/php/16' },
            { text: '命令行（CLI）开发指南', link: '/Code/php/17' },
            { text: '常用设计模式', link: '/Code/php/18' },
            { text: '多字节字符串处理（MBString）', link: '/Code/php/19' },
            { text: '邮件发送解决方案', link: '/Code/php/20' },
            { text: '图片处理（GD 库）', link: '/Code/php/21' },
            { text: '代码调试技巧', link: '/Code/php/22' },
          ]
        },
        {
          text: 'Node',
          collapsed: false,
          items: [
            { text: 'Node 部署', link: '/Code/node/index' },
            { text: 'Package.json Scripts 详解', link: '/Code/node/1' },
            { text: 'Node.js 模块系统详解 (CJS vs ESM)', link: '/Code/node/2' },
            { text: '异步编程入门：Callback、Promise 与 Async/Await', link: '/Code/node/3' },
            { text: 'Express.js 搭建 RESTful API 服务', link: '/Code/node/4' },
            { text: '中间件机制深入理解', link: '/Code/node/5' },
            { text: '文件上传处理 (Multer)', link: '/Code/node/6' },
            { text: '环境变量管理 (dotenv)', link: '/Code/node/7' },
            { text: 'JWT 身份认证实战', link: '/Code/node/8' },
            { text: '数据库操作：Sequelize ORM 入门', link: '/Code/node/9' },
            { text: '数据库操作：Prisma ORM 实战', link: '/Code/node/10' },
            { text: '输入验证与数据清洗 (Joi / Zod)', link: '/Code/node/11' },
            { text: '日志系统搭建 (Winston / Pino)', link: '/Code/node/12' },
            { text: '定时任务调度 (node-cron)', link: '/Code/node/13' },
            { text: 'WebSocket 实时通信 (Socket.io)', link: '/Code/node/14' },
            { text: '进程管理 (PM2) 生产部署', link: '/Code/node/15' },
            { text: 'Node.js Stream 流处理详解', link: '/Code/node/16' },
            { text: '单元测试 (Jest) 编写指南', link: '/Code/node/17' },
            { text: 'Node.js 事件循环 (Event Loop) 深度解析', link: '/Code/node/18' },
            { text: 'Buffer 与二进制数据处理', link: '/Code/node/19' },
            { text: 'child_process 子进程管理', link: '/Code/node/20' },
            { text: 'Cluster 模块实现多核利用', link: '/Code/node/21' },
            { text: '性能优化实战：内存泄漏排查', link: '/Code/node/22' },
            { text: '安全最佳实践 (Helmet, Rate Limiting)', link: '/Code/node/23' },
            { text: 'GraphQL API 搭建 (Apollo Server)', link: '/Code/node/24' },
            { text: 'Docker 容器化 Node.js 应用', link: '/Code/node/25' },
          ]
        },
        {
          text: 'Vue',
          collapsed: false,
          items: [
            { text: '前言', link: '/Code/vue/index' },
            { text: 'Vue 3 环境搭建与项目创建', link: '/Code/vue/1' },
            { text: '模板语法与响应式基础', link: '/Code/vue/2' },
            { text: '条件渲染与列表渲染', link: '/Code/vue/3' },
            { text: '事件处理与表单绑定', link: '/Code/vue/4' },
            { text: '组件基础 — Props、Emits 与 Slots 入门', link: '/Code/vue/5' },
            { text: 'Composition API 深入', link: '/Code/vue/6' },
            { text: '组件通信大全', link: '/Code/vue/7' },
            { text: 'Vue Router 路由实战', link: '/Code/vue/8' },
            { text: 'Pinia 状态管理入门', link: '/Code/vue/9' },
            { text: 'Composables 组合式函数', link: '/Code/vue/10' },
            { text: '插槽（Slots）详解', link: '/Code/vue/11' },
            { text: '组件注册与动态组件', link: '/Code/vue/12' },
            { text: '过渡与动画', link: '/Code/vue/13' },
            { text: 'TypeScript 与 Vue 3', link: '/Code/vue/14' },
            { text: '自定义指令', link: '/Code/vue/15' },
            { text: '插件开发', link: '/Code/vue/16' },
            { text: '表单验证方案', link: '/Code/vue/17' },
            { text: 'HTTP 请求管理', link: '/Code/vue/18' },
            { text: '国际化（i18n）', link: '/Code/vue/19' },
            { text: 'Vite 配置与优化', link: '/Code/vue/20' },
            { text: '组件测试', link: '/Code/vue/21' },
            { text: 'Nuxt 3 入门', link: '/Code/vue/22' },
            { text: '性能优化实战', link: '/Code/vue/23' },
            { text: '从零搭建后台管理项目', link: '/Code/vue/24' },
            { text: 'Vue 3 新特性与生态 2025', link: '/Code/vue/25' },
          ]
        },
        {
          text: 'JavaScript',
          collapsed: false,
          items: [
            { text: '前言', link: '/Code/js/index' },
            { text: 'JavaScript 运行环境与开发工具', link: '/Code/js/1' },
            { text: '变量声明与作用域', link: '/Code/js/2' },
            { text: '数据类型与类型转换', link: '/Code/js/3' },
            { text: '运算符与表达式', link: '/Code/js/4' },
            { text: '流程控制', link: '/Code/js/5' },
            { text: '函数', link: '/Code/js/6' },
            { text: '对象与原型链', link: '/Code/js/7' },
            { text: '数组操作大全', link: '/Code/js/8' },
            { text: '字符串与正则表达式', link: '/Code/js/9' },
            { text: 'DOM 操作与事件', link: '/Code/js/10' },
            { text: '异步编程', link: '/Code/js/11' },
            { text: 'JavaScript Event Loop 详解', link: '/Code/js/12' },
            { text: 'ES6+ 常用新特性', link: '/Code/js/13' },
            { text: '模块化（ESM）详解', link: '/Code/js/14' },
            { text: '错误处理与调试', link: '/Code/js/15' },
            { text: '浏览器存储方案', link: '/Code/js/16' },
            { text: 'Fetch API 与网络请求', link: '/Code/js/17' },
            { text: '事件循环与任务优先级', link: '/Code/js/18' },
            { text: '函数进阶：闭包、柯里化、高阶函数', link: '/Code/js/19' },
            { text: 'Proxy 与 Reflect', link: '/Code/js/20' },
            { text: '迭代器、生成器与可迭代协议', link: '/Code/js/21' },
            { text: 'Web API 实战', link: '/Code/js/22' },
            { text: '性能优化技巧', link: '/Code/js/23' },
            { text: '设计模式在 JavaScript 中的应用', link: '/Code/js/24' },
            { text: '现代 JavaScript 趋势 2025', link: '/Code/js/25' },
          ]
        },
      ],
      '/Server/': [
        {
          text: '服务器',
          collapsed: false,
          items: [
            { text: '前言', link: '/Server/index' },
            { text: '解决 Git Bash 连接 GitHub 超时问题 (443端口)', link: '/Server/1' },
            { text: 'Linux 常用命令速查手册', link: '/Server/2' },
            { text: 'SSH 免密登录配置指南', link: '/Server/3' },
            { text: 'Nginx 反向代理配置实战', link: '/Server/4' },
            { text: "Nginx HTTPS 证书配置 (Let's Encrypt)", link: '/Server/5' },
            { text: 'Docker 入门：从安装到第一个容器', link: '/Server/6' },
            { text: 'Docker Compose 多服务编排', link: '/Server/7' },
            { text: 'MySQL 数据库安装与基本配置', link: '/Server/8' },
            { text: 'MySQL 备份与恢复策略', link: '/Server/9' },
            { text: 'Redis 缓存服务器部署', link: '/Server/10' },
            { text: '防火墙配置 (UFW / iptables)', link: '/Server/11' },
            { text: 'Linux 用户与权限管理', link: '/Server/12' },
            { text: '定时任务 Crontab 实用指南', link: '/Server/13' },
            { text: '日志管理与分析', link: '/Server/14' },
            { text: '进程监控与故障排查', link: '/Server/15' },
            { text: '磁盘空间管理', link: '/Server/16' },
            { text: 'Shell 脚本自动化入门', link: '/Server/17' },
            { text: 'Git 服务器搭建（Gitea）', link: '/Server/18' },
            { text: 'CI/CD 流水线搭建（GitHub Actions）', link: '/Server/19' },
            { text: '服务器性能压测', link: '/Server/20' },
            { text: '系统资源监控（Prometheus + Grafana）', link: '/Server/21' },
            { text: '服务器安全加固清单', link: '/Server/22' },
            { text: '文件同步工具（rsync）详解', link: '/Server/23' },
            { text: 'DNS 配置与域名解析原理', link: '/Server/24' },
            { text: 'Kubernetes 入门：Pod 与 Deployment', link: '/Server/25' },
          ]
        }
      ],
      '/Design/': [
        {
          text: '设计',
          collapsed: false,
          items: [
            { text: '前言', link: '/Design/index' },
            { text: 'Figma 入门：从零开始你的第一个界面设计', link: '/Design/1' },
            { text: 'Figma 组件 (Components) 与变体 (Variants) 实战', link: '/Design/2' },
            { text: 'Auto Layout 自动布局完全指南', link: '/Design/3' },
            { text: '设计系统 (Design System) 构建方法论', link: '/Design/4' },
            { text: '色彩理论在 UI 设计中的应用', link: '/Design/5' },
            { text: '字体排版 (Typography) 设计原则', link: '/Design/6' },
            { text: '间距系统与网格 (Grid) 布局', link: '/Design/7' },
            { text: 'iOS 设计规范 (HIG) 核心要点', link: '/Design/8' },
            { text: 'Material Design 3 (Material You) 核心要点', link: '/Design/9' },
            { text: '图标设计原理与工具', link: '/Design/10' },
            { text: '微交互 (Micro-interaction) 设计指南', link: '/Design/11' },
            { text: 'Figma 原型 (Prototype) 交互连线', link: '/Design/12' },
            { text: '用户研究与用户画像创建', link: '/Design/13' },
            { text: '信息架构 (IA) 设计基础', link: '/Design/14' },
            { text: '响应式设计：多端适配策略', link: '/Design/15' },
            { text: '无障碍设计 (Accessibility) 入门', link: '/Design/16' },
            { text: '设计到开发：交付标注与切图规范', link: '/Design/17' },
            { text: 'UI 中的动效设计原则', link: '/Design/18' },
            { text: '暗黑模式 (Dark Mode) 设计指南', link: '/Design/19' },
            { text: '表单设计最佳实践', link: '/Design/20' },
            { text: '移动端导航模式全解析', link: '/Design/21' },
            { text: '设计评审 (Design Critique) 方法论', link: '/Design/22' },
            { text: 'AI 辅助设计工具实战', link: '/Design/23' },
            { text: '设计师的作品集搭建指南', link: '/Design/24' },
            { text: '设计趋势 2025-2026', link: '/Design/25' },
          ]
        }
      ],
      '/APP/': [
        {
          text: '应用',
          collapsed: false,
          items: [
            { text: '前言', link: '/APP/index' },
            { text: 'macOS 效率神器：Alfred 完全使用指南', link: '/APP/1' },
            { text: '笔记应用横向评测：Notion vs Obsidian vs Logseq', link: '/APP/2' },
            { text: '截图工具推荐：从 CleanShot X 到 Shottr', link: '/APP/3' },
            { text: 'Raycast：替代 Spotlight 的超级启动器', link: '/APP/4' },
            { text: '终端工具精选：Warp / iTerm2 / Tabby 对比', link: '/APP/5' },
            { text: '密码管理器推荐：1Password vs Bitwarden', link: '/APP/6' },
            { text: 'VS Code 必备插件清单 (2025)', link: '/APP/7' },
            { text: '文件管理工具：从 Finder 到 ForkLift', link: '/APP/8' },
            { text: '任务管理应用深度评测：Things vs Todoist vs TickTick', link: '/APP/9' },
            { text: '写作工具推荐：从 Ulysses 到 iA Writer', link: '/APP/10' },
            { text: "剪贴板管理工具：Maccy / Paste / Copy 'Em", link: '/APP/11' },
            { text: 'API 调试工具：Postman vs Insomnia vs HTTPie', link: '/APP/12' },
            { text: '数据库管理工具：TablePlus / DBeaver / Navicat', link: '/APP/13' },
            { text: '版本控制 GUI：Fork / Sourcetree / GitKraken 怎么选？', link: '/APP/14' },
            { text: '截图生成美化工具：Xnip / Picsew / Jietu 和更多选择', link: '/APP/15' },
            { text: '跨平台文件传输方案：从 AirDrop 到 LocalSend，选对工具不再折腾', link: '/APP/16' },
            { text: '阅读器应用推荐：从微信读书到 Readwise Reader', link: '/APP/17' },
            { text: '屏幕录制与 GIF 制作工具合集', link: '/APP/18' },
            { text: 'Markdown 编辑器全景评测', link: '/APP/19' },
            { text: '开发者浏览器：Edge / Brave / Arc / Zen 对比', link: '/APP/20' },
            { text: '窗口管理工具：Magnet / Rectangle / Moom 怎么选？', link: '/APP/21' },
            { text: 'AI 编程助手横向对比：Copilot / Cursor / Windsurf', link: '/APP/22' },
            { text: '团队协作工具：Linear / Notion / Lark', link: '/APP/23' },
            { text: '系统监控工具：iStat Menus / Stats / htop', link: '/APP/24' },
            { text: '年度应用推荐：2025 必装的精品应用', link: '/APP/25' },
          ]
        }
      ],
      '/Book/': [
        {
          text: '书籍',
          collapsed: false,
          items: [
            { text: '前言', link: '/Book/index' },
            { text: '经典书籍', link: '/Book/1' },
            { text: '如何写一篇深度书评：从阅读到输出的完整流程', link: '/Book/2' },
            { text: '推理小说入门指南：从本格到社会派', link: '/Book/3' },
            { text: '《三体》三部曲深度解读', link: '/Book/4' },
            { text: '科幻小说推荐：从小众到经典', link: '/Book/5' },
            { text: '村上春树作品导读', link: '/Book/6' },
            { text: '二战文学精选：在废墟中寻找人性', link: '/Book/7' },
            { text: '历史小说推荐：穿越时空的阅读体验', link: '/Book/8' },
            { text: '中国当代文学入门：80年代至今的重要作品', link: '/Book/9' },
            { text: '怎样阅读哲学书：写给非哲学专业的读者', link: '/Book/10' },
            { text: '短篇小说精选集：半小时读完的经典', link: '/Book/11' },
            { text: '日本文学入门：从夏目漱石到村田沙耶香', link: '/Book/12' },
            { text: '反乌托邦三部曲：《1984》《美丽新世界》《我们》', link: '/Book/13' },
            { text: '读书笔记方法论：如何让读过的书不再忘记', link: '/Book/14' },
            { text: '悬疑小说推荐：那些让你停不下来的翻页神器', link: '/Book/15' },
            { text: '魔幻现实主义书单：从马尔克斯到莫言', link: '/Book/16' },
            { text: '阅读速度提升技巧：从每分钟300字到800字', link: '/Book/17' },
            { text: '女性作家推荐书单：不可忽视的女性文学力量', link: '/Book/18' },
            { text: '诺贝尔文学奖得主作品导读', link: '/Book/19' },
            { text: "每月阅读计划制定指南：让阅读从「想」变成「在读」", link: '/Book/20' },
            { text: '英文原版书阅读入门：从分级到畅读', link: '/Book/21' },
            { text: '网络文学精品化：值得一读的网文推荐', link: '/Book/22' },
            { text: '建立个人图书馆：选书、购书与藏书指南', link: '/Book/23' },
            { text: '回忆录与传记精选：用他人的人生扩展自己的视野', link: '/Book/24' },
            { text: '年度阅读总结模板：如何回顾一年的阅读', link: '/Book/25' },
          ]
        }
      ],
      '/Video/': [
        {
          text: '视频',
          collapsed: false,
          items: [
            { text: '前言', link: '/Video/index' },
            { text: '奥斯卡最佳短片合集：20分钟改变你的世界观', link: '/Video/1' },
            { text: '纪录片入门推荐：从自然到人文的必看清单', link: '/Video/2' },
            { text: '导演风格解析：诺兰的电影叙事密码', link: '/Video/3' },
            { text: 'B站知识区宝藏UP主推荐', link: '/Video/4' },
            { text: '电影镜头语言入门：构图、运镜与色彩', link: '/Video/5' },
            { text: '经典电影配乐赏析：那些成就经典的BGM', link: '/Video/6' },
            { text: 'TED演讲精选：改变认知的经典演讲', link: '/Video/7' },
            { text: 'YouTube科技频道推荐：从科普到硬核工程', link: '/Video/8' },
            { text: '动画电影不只是给孩子的：深度动画推荐', link: '/Video/9' },
            { text: 'Vlog制作入门：从拍摄到剪辑', link: '/Video/10' },
            { text: '电影剪辑的艺术：从《爆裂鼓手》看节奏控制', link: '/Video/11' },
            { text: '程序员必看的技术视频频道', link: '/Video/12' },
            { text: '宫崎骏电影全集：观看顺序推荐指南', link: '/Video/13' },
            { text: '短视频创作方法论：从选题到爆款', link: '/Video/14' },
            { text: '电影中的光影艺术：罗杰·迪金斯摄影分析', link: '/Video/15' },
            { text: '年度最佳纪录片盘点（2024-2025）', link: '/Video/16' },
            { text: '综艺节目推荐：不止娱乐，更有深度', link: '/Video/17' },
            { text: '如何评价一部电影：影评写作入门指南', link: '/Video/18' },
            { text: 'Apple TV+ 精品剧集推荐', link: '/Video/19' },
            { text: '电影史入门：从默片到流媒体的关键转折', link: '/Video/20' },
            { text: '科幻电影推荐：兼具硬核与哲思的必看清单', link: '/Video/21' },
            { text: '电影字幕翻译的艺术：从理解到再创作', link: '/Video/22' },
            { text: '日本动画电影推荐：从今敏到新海诚', link: '/Video/23' },
            { text: '旅行纪录片推荐：不出门看世界', link: '/Video/24' },
            { text: '年度视频回顾：2025年最值得看的10支视频', link: '/Video/25' },
          ]
        }
      ],
      '/Other/': [
        {
          text: '其他',
          collapsed: false,
          items: [
            { text: '前言', link: '/Other/index' },
            { text: '🍸 调酒实验室', link: '/Other/cocktail-lab' },
            { text: '🎸 吉他研习社', link: '/Other/guitar-studio' },
            { text: '🎵 音乐万花筒', link: '/Other/music-kaleidoscope' },
            { text: '🌿 生活妙招集', link: '/Other/life-hacks' },
          ]
        }
      ],
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/binbin-design?tab=repositories' }
    ],
    search: {
        provider: 'local'
    },
    footer: {
        message: 'BinWind',
        copyright: 'Copyright © 2025 - 2026 present Evan You'
    },
  },
})